image: microsoft/dotnet:2-sdk

stages:
- build
- publish

build:
  stage: build
  script:
  - dotnet build
  - dotnet pack -c Release --include-symbols -o $CI_PROJECT_DIR/Build/
  artifacts:
    paths:
    - Build/*.nupkg
    expire_in: 1 week

publish:
  stage: publish
  when: manual
  script:
  - dotnet nuget push -k $NUGET_KEY $CI_PROJECT_DIR/Build/*.nupkg
  dependencies:
  - build