image: microsoft/dotnet:2-sdk

stages:
- build
- publish

build:
  stage: build
  script:
  - dotnet build
  - dotnet pack -c Release --include-symbols -o $CI_PROJECT_DIR/Build/
  artifacts:
    paths:
    - Build/*.nupkg
    expire_in: 1 week

publish:
  stage: publish
  when: manual
  script:
  - find $CI_PROJECT_DIR/Build/ -type f -name "*.nupkg" -not -name "*.symbols.nupkg" -exec dotnet nuget push -k $NUGET_KEY -s https://api.nuget.org/v3/index.json {} \;
  - find $CI_PROJECT_DIR/Build/ -type f -name "*.symbols.nupkg" -exec dotnet nuget push -k $NUGET_KEY -s https://nuget.smbsrc.net/ {} \;
  dependencies:
  - build